<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAE2Q5ee\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAE2Q5ee/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAE2Q5ee.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAE2Q5ee\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAE2Q5ee\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AE2Q5ee',
    'container.build_id' => '2ea6bbc8',
    'container.build_time' => 1552722118,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAE2Q5ee');
