<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSifQpGI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSifQpGI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSifQpGI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSifQpGI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSifQpGI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SifQpGI',
    'container.build_id' => 'cb5c0cf7',
    'container.build_time' => 1553155994,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSifQpGI');
