<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZIHNFs1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZIHNFs1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZIHNFs1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZIHNFs1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZIHNFs1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZIHNFs1',
    'container.build_id' => 'ff4ff4f5',
    'container.build_time' => 1553030465,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZIHNFs1');
